### ISSUE TITLE
No tokens passed to RoBERTa

### ISSUE THREAD

**Issue by maxmatical** [devkosal/tutorials#2]
After creating the learner, when I run `learn.fit` or `learn.lr_find()` I get the following warning:

`A sequence with no special tokens has been passed to the RoBERTa model. This model requires special tokens in order to work. Please specify add_special_tokens=True in your encoding.`

I have the data set up as follows
```

data_clas = TextDataBunch.from_df(".", df_train, df_val, 
                  tokenizer=fastai_tokenizer,
                  vocab=fastai_roberta_vocab,
                  text_cols="text",
                  label_cols='sentiment',
                  bs=bs,
                  collate_fn=partial(pad_collate, pad_first=False, pad_idx=0))

```

**Comment by maxmatical** [comment]
It looks like when I switch to the datablock method, the warning goes away, any ideas on why this is the case?

Thanks

**Comment by devkosal** [comment]
In the following approach, if you explicitly set the bs parameter, it should work fine (seems like you got it working as well since your edit)
```
data_clas = RobertaTextList.from_df(df, ".", cols=text_col, processor=processor) \
    .split_by_idxs(train_idx, val_idx) \
    .label_from_df(cols=label_col, label_cls=CategoryList) \
    .databunch(bs=bs, pad_first=False, pad_idx=0)
```

> It looks like when I switch to the datablock method, the warning goes away, any ideas on why this is the case?

Try using RobertaDataBunch instead of the TextDataBunch class:

```
data_clas = RobertaDataBunch.from_df(".", df_train, df_val, 
                  tokenizer=fastai_tokenizer,
                  vocab=fastai_roberta_vocab,
                  text_cols="text",
                  label_cols='sentiment',
                  bs=bs,
                  collate_fn=partial(pad_collate, pad_first=False, pad_idx=0))
```

**Comment by maxmatical** [comment]
That seems to fix it, thanks!
