### ISSUE TITLE
How would you learn.predict on a sentence pair?

### ISSUE THREAD

**Issue by e-ndrus** [devkosal/tutorials#4]
Thank you for the great tutorial. It seems to be working really good for me, but could you clarify how to make a prediction on a new unseen premise/hypothesis pair? Could you provide an example? Thank you!

**Comment by devkosal** [comment]
You can see an example of that in [this](https://github.com/devkosal/fastai_roberta/blob/master/fastai_roberta_superglue/RoBERTa%20with%20Fastai%20-%20CB.ipynb) notebook or [this](https://medium.com/analytics-vidhya/using-roberta-with-fastai-for-superglue-task-cb-c362961be957) tutorial where the test dataset is unseen and the CB task requires sentence pairs. If you want to execute the notebook, you can use these [scripts](https://github.com/nyu-mll/jiant/blob/master/tutorials/setup_tutorial.md) to get the appropriate data.

The key line where we add the test data is:
`.add_test(RobertaTextList.from_df(test, ".", cols=feat_cols, processor=processor)) `


To get the predictions:
`_, test_pred_values = get_preds_as_nparray(DatasetType.Test) `
