### ISSUE TITLE
Databunch load error

### ISSUE THREAD

**Issue by harshikanu** [devkosal/tutorials#5]
Hi,

I am trying to save the databunch using data.save() and loading it 
data = load_data(path, ‘databunch.pkl’)
I am getting a warning and an error —

A sequence with no special tokens has been passed to the RoBERTa model. This model requires special tokens in order to work. Please specify add_special_tokens=True in your encoding.
IndexError: index out of range in self in
preds = learn.get_preds(DatasetType.Valid)[0].detach().cpu().numpy()

Could you please help me with this?

**Comment by devkosal** [comment]
I am not sure why `preds` is being defined in this step. In any case, doing the following worked for me to save and load the data bunch. Try using this code underneath directly after [step 3](https://medium.com/analytics-vidhya/using-roberta-with-fastai-for-nlp-7ed3fed21f6c). 

```
# creating our databunch 
data = RobertaTextList.from_df(df, ".", cols=feat_cols, processor=processor) \
    .split_by_rand_pct(seed=config.seed) \
    .label_from_df(cols=label_cols,label_cls=CategoryList) \
    .databunch(bs=config.bs, pad_first=False, pad_idx=0)

# save the data as data_save.pkl
data.save("data_save.pkl")

# load the pkl file into a new object to test if it works
data_new = load_data(".")
```

**Comment by harshikanu** [comment]
Thanks ! I’ll definitely try that. 

I have one more question. 
Right now I am trying to predict sentiments real-time and it takes about 2-3 hours for the results. 
Is there a way  that I can make the process more efficient?

**Comment by devkosal** [comment]
Are you retraining the model each time you want predictions? Or are you using pretrained weights?

**Comment by harshikanu** [comment]
I want to load a pre-trained model (along with the databunch).

**Comment by devkosal** [comment]
I usually save the model weights using:
```
st = learn.model.state_dict()
torch.save(st, "model_file_name") # will save model in current dir
```
And load (in my deployment script) using:
```
roberta_model = CustomRobertatModel()
st = torch.load("model_file_name")
roberta_model.load_state_dict(st) # you can also load this into learn.model instead of roberta_model
```

**Comment by harshikanu** [comment]
This is what I am doing, do get preds. 

    
data1 = load_data(
        path, 'data_save.pkl')
    roberta_model = CustomRobertaModel()
    st2 = torch.load("../input/model-and-databunch/final_model_base.pth"
                     ,map_location=torch.device('cpu')
                    )

    roberta_model.load_state_dict(st2)
    roberta_model.eval()
    preds = roberta_model.get_preds(DatasetType.Valid)[0].detach().cpu().numpy()
    sampler = [i for i in data1.dl(DatasetType.Valid).sampler]
    reverse_sampler = np.argsort(sampler)
    ordered_preds = preds[reverse_sampler, :]
    pred_values = np.argmax(ordered_preds, axis=1)
    # preds, pred_values = get_preds_as_nparray(DatasetType.Valid)

    # accuracy on valid
    (pred_values == data1.valid_ds.y.items).mean()

    for message in data_df['message']:
        result_test = learn.predict(message)
        final_result.append(result_test)

But I get the error "AttributeError: 'CustomRobertaModel' object has no attribute 'get_preds'"

Can you help me with this?

**Comment by harshikanu** [comment]
https://www.kaggle.com/harshinikanukuntla/sentiment-roberta

If it helps, this is my workbook!

**Comment by devkosal** [comment]
That is happening because CustomRobertaModel is not a fastai learner object. In order to get preds from CustomRobertaModel, you have to either implement a custom get preds function or you can use a learner (as we do in training):
```
learn.model.load_state_dict(st2)
learn.model.eval()
preds = learn.get_preds(DatasetType.Valid)[0].detach().cpu().numpy()
```

**Comment by harshikanu** [comment]
Would I get the same predicts if i do -

learn.model.load_state_dict(st2)
learn.model.eval()
result_test = learn.predict(message)

in place of get_preds() ?

May I know the difference?

**Comment by devkosal** [comment]
These are both fastai methods. Although they both get predictions, you would not get the same results. You can view the differences [here](https://docs.fast.ai/basic_train.html#Learner.predict).

**Comment by harshikanu** [comment]
When I run the file on Production, after loading the databunch and the training model, 
I get the error "AttributeError: Can't get attribute 'RobertaTextList' on <module '__main__' from 'manage.py'>".

Can you help me with this?

**Comment by devkosal** [comment]
You may need to either import or redefine the RobertaTextList object in your Production code. The same applies for all other such Attribute errors.

**Comment by harshikanu** [comment]
Can you please elaborate?

**Comment by devkosal** [comment]
Have you defined RobertaTextList in your Production code prior to the line which generates this error?

**Comment by harshikanu** [comment]
Yes! 

class RobertaTextList(TextList):
    _bunch = RobertaDataBunch
    _label_cls = TextList

**Comment by devkosal** [comment]
Great! If you could please share the code lines around which the error is generated, I can try to debug.

**Comment by harshikanu** [comment]
I have somehow fixed that error. Thanks for the help :)

Now I am getting a warning "A sequence with no special tokens has been passed to the RoBERTa model. This model requires special tokens in order to work. Please specify add_special_tokens=True in your encoding."

I've tried adding .encode(add_special_tokens=True) to RobertaTokenizer but I still get the warning. 
I even tried adding it in config. 

Is there any way I can overpass this warning?

**Comment by harshikanu** [comment]
> Great! If you could please share the code lines around which the error is generated, I can try to debug.

Getting the error again, but this time when I scheduled the task with Celery.

  File "run_analysis.py", line 177, in run_alerts
    alerts = alerts_roberta(alert_df)
  File "alerts_roberta.py", line 255, in alerts_roberta
    data = load_data(path, r"/home/alerts/databunch.pkl")
  File "/usr/local/lib/python3.7/site-packages/fastai/basic_data.py", line 281, in load_data
    ll = torch.load(source, map_location='cpu') if defaults.device == torch.device('cpu') else torch.load(source)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
AttributeError: Can't get attribute 'RobertaTextList' on <module 'celery.bin.celery' from '/usr/local/lib/python3.7/site-packages/celery/bin/celery.py'>

**Comment by harshikanu** [comment]
"[2020-05-08 00:20:58,033: ERROR/ForkPoolWorker-1] Task run_alerts[c4cde7dc-8cba-4411-827f-3ecc1d216643] raised unexpected: AttributeError("Can't get attribute 'RobertaTextList' on <module 'celery.bin.celery' from '/usr/local/lib/python3.7/site-packages/celery/bin/celery.py'>")
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
R = retval = fun(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 650, in protected_call
return self.run(*args, **kwargs)
File "/home/run_analysis.py", line 177, in run_alerts
alerts = alerts_roberta(alert_df)
File "/home/alerts_roberta.py", line 259, in alerts_roberta
path, r"/home/data_save.pkl", torch.device('cpu'))
File "/usr/local/lib/python3.7/site-packages/fastai/basic_data.py", line 281, in load_data
ll = torch.load(source, map_location='cpu') if defaults.device == torch.device('cpu') else torch.load(source)
File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 702, in _legacy_load
result = unpickler.load()
AttributeError: Can't get attribute 'RobertaTextList' on on <module 'main' from 'manage.py'>".

This is the error I am getting. I think the function isn't able to call the RobertaTextList object defined in the file. Just to add to that, the error is when I am trying to load the databunch file which was created using RobertaTextList.from_df.

Also, I am getting a warning "A sequence with no special tokens has been passed to the RoBERTa model. This model requires special tokens in order to work. Please specify add_special_tokens=True in your encoding."

I've tried adding .encode(add_special_tokens=True) to RobertaTokenizer but I still get the warning.
I even tried adding it in config.

Is there any way I can overpass this warning?

**Comment by devkosal** [comment]
I can't pinpoint the exact issue here but you should make sure all RobertaTextList dependencies are met prior to loading the pickle wherever you are using RobertaTextList. Just to be safe, I would import (or define) all dependencies in each of your scripts. Once you get it to work, you can remove unneeded dependencies. 

As for the warning, are you receiving it while running the `Using RoBERTa with Fastai Tutorial.ipynb` notebook and/or within your production script?

**Comment by harshikanu** [comment]
I am receiving it with the production script. 

I tried importing it by putting all the custom classes in utils.py and then importing it. But nothing seems to work.

**Comment by devkosal** [comment]
That's bizarre. I'm not sure what else could be the issue in your prod script. Sorry I'm not of more help.

**Comment by harshikanu** [comment]
Now I am trying to predict the sentiment of a sentence by using learn.predict(message). But I am getting the following error -

    result_test = learn.predict(message)
File “/usr/local/lib/python3.7/site-packages/fastai/basic_train.py” in predict
382. y = ds.y.reconstruct(pred, x) if has_arg(ds.y.reconstruct, ‘x’) else ds.y.reconstruct(pred)

File “/usr/local/lib/python3.7/site-packages/fastai/text/data.py” in reconstruct
341. return Text(t[idx_min:idx_max+1], self.vocab.textify(t[idx_min:idx_max+1]))

File “/usr/local/lib/python3.7/site-packages/fastai/text/transform.py” in textify
134. return sep.join([self.itos[i] for i in nums]) if sep is not None else [self.itos[i] for i in nums]

File “/usr/local/lib/python3.7/site-packages/fastai/text/transform.py” in
134. return sep.join([self.itos[i] for i in nums]) if sep is not None else [self.itos[i] for i in nums]

Exception Type: TypeError at /test_sent/
Exception Value: only integer tensors of a single element can be converted to an index

**Comment by harshikanu** [comment]
Thanks for the help. 
However, to make a note, with the new fastaiv2 being released, most of the code has changed. :)
